# Runs compile check, linter, and tests on PRs from members with write access.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  ci:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.author_association == 'OWNER' ||
      github.event.pull_request.author_association == 'MEMBER' ||
      github.event.pull_request.author_association == 'COLLABORATOR'
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff
    - name: Compile check
      run: python -m compileall rdflib_neo4j/
    - name: Lint
      run: ruff check rdflib_neo4j/ test/unit/
    - name: Test with pytest
      run: |
        pytest